// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaHouseShop.Models;

#nullable disable

namespace PizzaHouseShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241005214201_AddData")]
    partial class AddData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PizzaHouseShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Vegan pizza",
                            Description = "Short description"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Ham pizza",
                            Description = "Short description"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Chesse pizza",
                            Description = "Short description"
                        });
                });

            modelBuilder.Entity("PizzaHouseShop.Models.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PizzaId"), 1L, 1);

                    b.Property<string>("AllergyInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPizzaOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PizzaId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pizza");

                    b.HasData(
                        new
                        {
                            PizzaId = 1,
                            AllergyInformation = "No allergens",
                            CategoryId = 1,
                            ImageThumbnailUrl = "",
                            ImageUrl = "",
                            InStock = true,
                            IsPizzaOfTheWeek = false,
                            LongDescription = "Regardess what else comes atop your pizza, a few fresh basil leaves will taste amazing with it. This simple sumertime pizza would make a delicious cookout appetizer or light dinner paired with a salad.",
                            Name = "Fresh Basil pizza",
                            Price = 15.95m,
                            ShortDescription = "Grilled Tomato-Peach Pizza"
                        },
                        new
                        {
                            PizzaId = 2,
                            AllergyInformation = "Gluten",
                            CategoryId = 3,
                            ImageThumbnailUrl = "",
                            ImageUrl = "",
                            InStock = true,
                            IsPizzaOfTheWeek = true,
                            LongDescription = "The Extra Cheese pizza is a deliciously rich option featuring a generous layer of melted mozzarella, creating a gooey, savory bite in every slice. Its cheesy goodness makes it a perfect comfort food for cheese lovers.",
                            Name = "Extra Cheese pizza",
                            Price = 16.95m,
                            ShortDescription = "Deep-Dish Skillet Pizza"
                        },
                        new
                        {
                            PizzaId = 3,
                            AllergyInformation = "No allergens",
                            CategoryId = 2,
                            ImageThumbnailUrl = "",
                            ImageUrl = "",
                            InStock = false,
                            IsPizzaOfTheWeek = false,
                            LongDescription = "The Ham pizza offers a savory combination of tender, smoky ham slices atop a crispy crust, layered with tangy tomato sauce and melted cheese. This classic pizza brings a satisfying balance of flavors.",
                            Name = "Ham pizza",
                            Price = 17.95m,
                            ShortDescription = "Fig, Ham, and Ricotta Pizza"
                        },
                        new
                        {
                            PizzaId = 4,
                            AllergyInformation = "Gluten",
                            CategoryId = 2,
                            ImageThumbnailUrl = "",
                            ImageUrl = "",
                            InStock = true,
                            IsPizzaOfTheWeek = false,
                            LongDescription = "The Sausage pizza features flavorful, seasoned sausage crumbles scattered over a bed of melted cheese and tangy tomato sauce. Its robust, savory taste makes it a hearty option.",
                            Name = "Sausage pizza",
                            Price = 14.95m,
                            ShortDescription = "Sausage and Kale Pesto Pizza"
                        });
                });

            modelBuilder.Entity("PizzaHouseShop.Models.Pizza", b =>
                {
                    b.HasOne("PizzaHouseShop.Models.Category", "Category")
                        .WithMany("Pizzas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PizzaHouseShop.Models.Category", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
